---
# Download and install Remi for Centos/RHEL version 7
- name: Download Remi Repo - Centos/RHEL 7
  get_url: url={{ remiRepository }} dest=/tmp/remi-release-7.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install Remi Repo - Centos/RHEL 7
  yum:
    name: /tmp/remi-release-7.noarch.rpm
    state: present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
